### ISSUE TITLE
About F-score

### ISSUE THREAD

**Issue by GNN-zl** [zhumeiqiBUPT/AM-GCN#1]
Hi, I have two problems about it. Can you help me?
When I input 'python main.py -d citeseer -l 20 ', It says 'UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples'. How to deal with it?
And the result is ' epoch:12 acc_max: 0.7380 f1_max: 0.6999 '. It is little higher than the result in your paper. I don't know whether it is associated with the warning above.

**Comment by zhumeiqiBUPT** [comment]
Hi, Thanks for your attention to our work. In my opinion, this "warning" is different from "error" and it doesn't affect our results. In our experiments, we just ignore this warning and random run AM-GCN five times to get the final results.
If you don't want to see this warning, you can insert the following codes:
`import warnings`
`warnings.filterwarnings("ignore")`

**Comment by GNN-zl** [comment]
Thanks for your reply.
