### ISSUE TITLE
Code issues

### ISSUE THREAD

**Issue by xnuohz** [zhumeiqiBUPT/AM-GCN#10]
Hi,
I am a little confused about [this line](https://github.com/zhumeiqiBUPT/AM-GCN/blob/1ce29649f47a67e27b89337cc37eb67ba096308a/AMGCN/utils.py#L109), could you explain it? And it seems that [this line](https://github.com/zhumeiqiBUPT/AM-GCN/blob/1ce29649f47a67e27b89337cc37eb67ba096308a/AMGCN/utils.py#L115) doesn't influence the result if I remove it.
Thanks:)

**Comment by zhumeiqiBUPT** [comment]
Hello, 
these two lines are used for building symmetric adjacency matrices, which are the same with that in [pygcn](https://github.com/tkipf/pygcn/blob/master/pygcn/utils.py). Since our input sadj are already symmetric adjacency matrices, it doesn't influence the result.

**Comment by xnuohz** [comment]
Thanks for your reply. KNN graph should be symmetric too, so it also doesn't influence the result if [this line](https://github.com/zhumeiqiBUPT/AM-GCN/blob/1ce29649f47a67e27b89337cc37eb67ba096308a/AMGCN/utils.py#L109) is removed. But accuracy is 72.0 instead of 73.3 when I run `python main.py -d citeseer -l 20`,  do I misunderstand something?

**Comment by zhumeiqiBUPT** [comment]
Please note that edge files in folder "/data/dataname/knn/" for KNN graph just write each edge for one time, which means the input graph is not symmetric before processing. The edge files in folder "/data/dataname/XX.edge" write each edge for two times, so the input graph is symmetric. 
Anyway, you can always keep these two lines just in case.
