### ISSUE TITLE
这个可以用于异构图吗？

### ISSUE THREAD

**Issue by Heath0** [zhumeiqiBUPT/AM-GCN#13]

**Comment by Heath0** [comment]
您好，我想问下，如果我的数据集是个二部图的邻接矩阵和两类节点的特征向量。还能把该方法用在这种数据集上吗？

**Comment by Heath0** [comment]
您好，我想问如果是二部图的话，怎么构建knn特征图呢？

**Comment by zhumeiqiBUPT** [comment]
knn特征图的构建主要取决于节点的特征，可以考虑用user的feature或者item的feature构建对应的user knn以及item knn。

另外，异构图也可以考虑根据meta-path游走出多个子图，抽取公共部分和特定部分。这篇论文的思想和这个类似：[Heterogeneous Information Network Embedding with Adversarial Disentangler](http://shichuan.org/doc/112.pdf)
