### ISSUE TITLE
训练为什么不用验证集

### ISSUE THREAD

**Issue by lizhou21** [zhumeiqiBUPT/AM-GCN#14]
你好，我想咨询一下，为什么训练只用了训练集和测试集，而且在每个训练epoch中进行test，选择最好的test作为实验数据，这似乎并不符合实验的标准。

**Comment by zhumeiqiBUPT** [comment]
我们在论文中report的结果不是这里代码展示最好的test结果，而是取固定epoch的最终输出，这点在之前的issue中也有提过。
