### ISSUE TITLE
About baseline performance

### ISSUE THREAD

**Issue by LiFXe** [zhumeiqiBUPT/AM-GCN#6]
I am confused why the performance of mixhop is significantly worse than some older baselines, is this because of the data?

**Comment by zhumeiqiBUPT** [comment]
Yes, I think so.

**Comment by zhumeiqiBUPT** [comment]
For example, for the BlogCatalog and Flickr datasets, MixHop has similar performance with GCN, since they all propagate feature along topology graph not feature graph, the only difference is that MixHop just concate high order information from topology graph which may help in some case.

**Comment by LiFXe** [comment]
OK, thanks a lot~
