### ISSUE TITLE
About the feature graph construction

### ISSUE THREAD

**Issue by ZJJTSL** [zhumeiqiBUPT/AM-GCN#7]
i wonder to know how to construct the feature graph, i can't make it clear how to get the 'citeseer.feature' file  in the processdata.py  , look forward for  your help,thanks!

**Comment by zhumeiqiBUPT** [comment]
Hello, you can run `process_data()` in `dataprocess.py` to generate the 'citeseer.feature' file, using the original data files in [gcn](https://github.com/tkipf/gcn/tree/master/gcn/data) as input. But actually, we have already provided the feature file in **citeseer.zip**, and you just need to **unzip** it first. Then `generate_knn()` is used for constructing feature graph.

**Comment by ZJJTSL** [comment]
> Hello, you can run `process_data()` in `dataprocess.py` to generate the 'citeseer.feature' file, using the original data files in [gcn](https://github.com/tkipf/gcn/tree/master/gcn/data) as input. But actually, we have already provided the feature file in **citeseer.zip**, and you just need to **unzip** it first. Then `generate_knn()` is used for constructing feature graph.

yeah,i've noticed the citeseer.zip,but i want to how to make it for a new dataset . In the dataprocess.py line 20, i don't know which file is opened, thanks!

**Comment by Noval11** [comment]
> > Hello, you can run `process_data()` in `dataprocess.py` to generate the 'citeseer.feature' file, using the original data files in [gcn](https://github.com/tkipf/gcn/tree/master/gcn/data) as input. But actually, we have already provided the feature file in **citeseer.zip**, and you just need to **unzip** it first. Then `generate_knn()` is used for constructing feature graph.
> 
> yeah,i've noticed the citeseer.zip,but i want to how to make it for a new dataset . In the dataprocess.py line 20, i don't know which file is opened, thanks!

I have the same quesion. Looking forward to your answer! Thanks!

**Comment by zhumeiqiBUPT** [comment]
Hello, I think I've already given the explanation. The original data files in https://github.com/tkipf/gcn/tree/master/gcn/data is opened as input. You just need download and store them in data/cache/ folder before running dataprocess.py

**Comment by Noval11** [comment]
Yes, you are right, I find it. Thank you!
