### ISSUE TITLE
特征图构建

### ISSUE THREAD

**Issue by ZJJTSL** [zhumeiqiBUPT/AM-GCN#8]
您好，想问下自己的数据集的话如何去构建特征图呢

**Comment by zhumeiqiBUPT** [comment]
您好，可以以节点特征矩阵作为输入，使用dataprocess.py中的generate_knn函数构建特征KNN图。

**Comment by ZJJTSL** [comment]
您好，还想问下 构建feature的话 如果我是n个顶点（无向图） 以顶点的度来构建特征图的话 feature就是n*1的shape吗。 非常感谢！！

**Comment by zhumeiqiBUPT** [comment]
> 您好，还想问下 构建feature的话 如果我是n个顶点（无向图） 以顶点的度来构建特征图的话 feature就是n*1的shape吗。 非常感谢！！

不好意思回复晚了。特征矩阵的shape还是要取决于想怎么使用节点的度：如果使用节点度的数值，则是N\*1；如果使用基于节点度的one-hot向量，则shape是N\*M(M是最大的节点度数)
