### ISSUE TITLE
I want to know if the authors have any experimental results on Cora and PubMed datasets. I spend a lot of time adjusting parameters to modify your code, but it is still difficult to get ideal results, even worse than the results of GCN on Cora and PubMed. Secondly, this paper does not use validation dataset, and outputs the best results on the test dataset. Is it reasonable?

### ISSUE THREAD

**Issue by njuyuan** [zhumeiqiBUPT/AM-GCN#9]

**Comment by zhumeiqiBUPT** [comment]
Hello, we did not have experimental results for Cora and Pubmed, while we test AM-GCN on another six datasets. 
 
And, we did not output the best results for experiments in our paper, we just fix the training epoch and run 5 times for average with random seeds.  And I think I have already mention this in the pervious issue #1. 

Actually, we just want show the performance of AM-GCN in github and choose to report the best test result in this version.  And it is little higher than the results in our paper.

It is obvious that you can change the  experiment settings if you need, and just make them same among baselines.

**Comment by njuyuan** [comment]
> Hello, we did not have experimental results for Cora and Pubmed, while we test AM-GCN on another six datasets.
> 
> And, we did not output the best results for experiments in our paper, we just fix the training epoch and run 5 times for average with random seeds. And I think I have already mention this in the pervious issue #1.
> 
> Actually, we just want show the performance of AM-GCN in github and choose to report the best test result in this version. And it is little higher than the results in our paper.
> 
> It is obvious that you can change the experiment settings if you need, and just make them same among baselines.

Thanks.
